version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "quarterly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: quarterly
    groups:
      all:
        patterns:
          - "*"
