repos:
# Syntax validation and some basic sanity checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-ast
    fail_fast: True
  - id: check-json
  - id: check-added-large-files
    args: ['--maxkb=200']
  - id: check-yaml

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.286
  hooks:
    - id: ruff
      args: [--fix, --show-fixes, --exit-non-zero-on-fix]

# Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    args: [--safe, --quiet]

# Type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
  - id: mypy
    files: 'src/.*\.py$'
    additional_dependencies:
    - types-requests
    - types-pkg_resources
    - types-pyyaml

- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  additional_dependencies: ["poetry-plugin-export"]
  hooks:
    - id: poetry-lock
    - id: poetry-export
      args: [-o, requirements_dev.txt, --with=dev, --without-hashes]