ci:
  autoupdate_schedule: quarterly

repos:
# Syntax validation and some basic sanity checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: check-ast
    fail_fast: True
  - id: check-json
  - id: check-added-large-files
    args: ['--maxkb=200']
  - id: check-yaml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    - id: ruff
      args: [--fix, --show-fixes, --exit-non-zero-on-fix]
    - id: ruff-format

# Type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
    files: 'src/.*\.py$'
    additional_dependencies:
    - types-requests
    - types-pyyaml

- repo: https://github.com/python-poetry/poetry
  rev: 1.8.0
  hooks:
    - id: poetry-lock
    - id: poetry-export
      additional_dependencies: [poetry-plugin-export]
      args: [-o, requirements_dev.txt, --with=dev, --without-hashes]
