# Config file for automatic testing at travis-ci.com

language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 2.7
    - python: pypy
    - os: osx
      language: generic
      env: PYTHON=3.7.1 TOXENV=py37
    - os: osx
      language: generic
      env: PYTHON=2.7.15 TOXENV=py27

  allow_failures:
    - env: OPTIONAL=1

  fast_finish: true

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
    brew install openssl readline
    # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
    # I didn't do this above because it works and I'm lazy.
    brew outdated pyenv || brew upgrade pyenv
    # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
    # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
    # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
    # modify the Bash environment. ??? So, I hand-set the variables instead.
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
  fi

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --pro --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mgerstel
  password:
    secure: dgQ1nDyglzeQSpdEplBUMwvfi58vkPHYR4L5oJX8yQZpTjquOXlsjgUXQihFLh+fFEuCMiv0TqZIt2VmHPZSHeOUe3YNdMRV2ty4XqpjlE6+R6TPAbjrY9AwVOvDg/GHKUyXMGAVhq1wOEGhX+WDKOXNR1qfwCjyODSLw6peu2JPwZM5iFC9pCirio/wQOGDlKuhBGpQeOB95P7MEDLk9gIpn5nZOPQ6g3fcApzssM/c2sLsnHBB7wFEpRW7cJGFjn4VxmxpdSQlvujxRsEQrZtp0jyRYFExlcYGB4QyMlaS/Pp69ffFZ64n10tOhIeC8u0T20hInuEXqnivy8NWNjuZL/OJJEdWp7wwWyUOQhNwdlgBV/apesysXZgRRF4MMLTyZNulfOP/2lVr6eEpo28Qq+OjwgsEpAW8XEuKE4qCwf99m4vk2PwBoMO70CMokrpMT00q2r/m5IDQfsbov8bK0VQ6ZiMpB9rLDguv9/l2qAMAFLQARDQ9YwVYkGPep+jKpz74ShOxAFhidWDk7Q1gkz72s6ukQM5HLUlYohYWhfsqLY9K9uaq2GEGb/ZZY3IRFPWROqXlOVRjexjVML5peE9YPlz+qyiAs+J6ZtSR4dCdsd3UeJJLIVYK4VOvGoVa+suFMwDWFnsriARUDSvok7DBFoPOHQp896/vQlA=
  on:
    tags: true
    repo: DiamondLightSource/zocalo-python
    python: 3.7
