apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zocalo
  title: Zocalo
  description: >
    Infrastructure components for automated data processing via a messaging
    framework.
  annotations:
    github.com/project-slug: DiamondLightSource/python-zocalo
    diamond.ac.uk/viewdocs-url: https://zocalo.readthedocs.io
  tags:
    - python
spec:
  type: library
  lifecycle: production
  owner: group:data-analysis
  dependsOn:
    - resource:zocalo-rabbitmq
    - component:workflows
