version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "monthly"
    ignored_updates:
      # mock 4 requires Python 3.6+
      - match:
          dependency_name: "mock"
          version_requirement: ">=4"
      # twine 2 requires Python 3.6+
      - match:
          dependency_name: "twine"
          version_requirement: ">=2"
