name: "Linting"

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Ruff Check
      uses: jpetrucciani/ruff-check@50ac1dd6ce54199faf44cb3b1d8f5a892a548069 # 0.15.12
