name: "Linting"

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ruff Check
      uses: jpetrucciani/ruff-check@0a3ff56b5c6ad23d2ee9751dfa4e00d2d55b61a8 # 0.12.2
