name: "Linting"

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ruff Check
      uses: jpetrucciani/ruff-check@3d1a50730e90a5cb0347ec031202041376542e07 # 0.15.5
