name: "Linting"

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Ruff Check
      uses: jpetrucciani/ruff-check@19e86bc4be4bb4a5b87b5aedbc6d5989cc777a70 # 0.16.9
